name: Execução Manual

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # clone do projeto
      - uses: actions/checkout@v4
      
      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
      
      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn
      
      # instalação das dependências
      - name: Instalando dependências
        run: yarn
      
      # executar testes unitários
      - name: Executando Testes Unitários
        run: yarn test
      
      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install
      
      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e